name: dni_nie_validator
description: A dart package to validate if the DNI or NIE entered is valid in format and calculate the corresponding letter.
version: 0.0.2
homepage: https://github.com/AnnaPS/dni_nie_validator


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

